CREATE SCHEMA taxi_management;
SET search_path TO taxi_management;

CREATE TABLE MANAGER(
	NAME TEXT,
	SSN CHARACTER(9),
	EMAIL TEXT,

	CONSTRAINT manager_pkey PRIMARY KEY (SSN)
);

CREATE TABLE ADDRESS(
	ROAD TEXT,
	NUMBER TEXT,
	CITY TEXT,

	CONSTRAINT address_pkey PRIMARY KEY (ROAD, NUMBER, CITY)
);


CREATE TABLE CLIENT(
	NAME TEXT, 
	EMAIL TEXT,

	CONSTRAINT client_pkey PRIMARY KEY (EMAIL)
);

CREATE TABLE DRIVER(
	NAME TEXT,

	ROAD TEXT NOT NULL,
	NUMBER TEXT NOT NULL,
	CITY TEXT NOT NULL,
	
	CONSTRAINT driver_pkey PRIMARY KEY (NAME),
	CONSTRAINT driver_address_fkey FOREIGN KEY (ROAD, NUMBER, CITY) REFERENCES ADDRESS(ROAD, NUMBER, CITY)
);

CREATE TABLE CAR(
	CAR_ID INT, 
	BRAND TEXT,
	
CONSTRAINT car_pkey PRIMARY KEY (CAR_ID)
);

CREATE TABLE MODEL(
	MODEL_ID INT,
	TRANSMISSION TEXT,
	YEAR INT, 
	COLOR TEXT,

	CAR_ID INT,

    CONSTRAINT model_pkey PRIMARY KEY (MODEL_ID, CAR_ID),
    CONSTRAINT model_car_fkey FOREIGN KEY (CAR_ID) REFERENCES CAR(CAR_ID)
);

CREATE TABLE RENT(
	RENT_ID INT,
	RENT_DATE DATE,

	EMAIL TEXT NOT NULL,

	NAME TEXT NOT NULL,

	MODEL_ID INT NOT NULL,
	CAR_ID INT NOT NULL,

	CONSTRAINT rent_pkey PRIMARY KEY (RENT_ID),
	CONSTRAINT rent_client_fkey FOREIGN KEY (EMAIL) REFERENCES CLIENT(EMAIL),
	CONSTRAINT rent_driver_fkey FOREIGN KEY (NAME) REFERENCES DRIVER(NAME),
	CONSTRAINT rent_model_fkey FOREIGN KEY (MODEL_ID, CAR_ID) REFERENCES MODEL(MODEL_ID, CAR_ID)
);

CREATE TABLE REVIEW(
	REVIEW_ID INT,
	RATING INT,
	MESSAGE TEXT,
	
	NAME TEXT NOT NULL,

	EMAIL TEXT NOT NULL,

	CONSTRAINT review_pkey PRIMARY KEY (REVIEW_ID, NAME),
	CONSTRAINT review_driver_fkey FOREIGN KEY (NAME) REFERENCES DRIVER(NAME),
	CONSTRAINT review_client_fkey FOREIGN KEY (EMAIL) REFERENCES CLIENT(EMAIL)
);

CREATE TABLE CREDIT_CARD(
	NUMBER CHARACTER(16),

	EMAIL TEXT,

	ROAD TEXT NOT NULL,
	NUMBER_ADDR TEXT NOT NULL,
	CITY TEXT NOT NULL,

	CONSTRAINT creditcard_pkey PRIMARY KEY (NUMBER),
	CONSTRAINT creditcard_client_fkey FOREIGN KEY (EMAIL) REFERENCES CLIENT(EMAIL),
	CONSTRAINT creditcard_address_fkey FOREIGN KEY (ROAD, NUMBER_ADDR, CITY) REFERENCES ADDRESS(ROAD,NUMBER,CITY)
);


CREATE TABLE HasAddress(
    EMAIL TEXT,

    ROAD TEXT NOT NULL,
    NUMBER TEXT NOT NULL,
    CITY TEXT NOT NULL,

    CONSTRAINT hasaddress_pkey PRIMARY KEY(EMAIL, ROAD, NUMBER, CITY),
    CONSTRAINT hasaddress_client_fkey FOREIGN KEY (EMAIL) REFERENCES CLIENT(EMAIL),
    CONSTRAINT hasaddress_address_fkey FOREIGN KEY (ROAD, NUMBER, CITY) REFERENCES ADDRESS(ROAD,NUMBER,CITY)
);

CREATE TABLE CAN_DRIVE (
	NAME TEXT,

	MODEL_ID INT NOT NULL,
	CAR_ID INT NOT NULL,
	
    CONSTRAINT candrive_pkey PRIMARY KEY (NAME, MODEL_ID, CAR_ID),
    CONSTRAINT candrive_driver_fkey FOREIGN KEY (NAME) REFERENCES DRIVER(NAME),
    CONSTRAINT candrive_model_fkey FOREIGN KEY (MODEL_ID, CAR_ID) REFERENCES MODEL(MODEL_ID, CAR_ID)
);

